### ISSUE TITLE
Without maximizing the window, the Credits Button isn't matched with the window.

### ISSUE THREAD

**Issue by ThePlayerZero** [ThePlayerZero/Open-Fantasy#14]
![toontown-screenshot-Wed-Jul-06-00-47-24-2022-9271](https://user-images.githubusercontent.com/68795576/177470946-406df2cc-02a6-4723-9062-4c62ccbad710.jpg)

**Comment by DarthNihilus1** [comment]
Easy parent it to aspect 2d then position it based on that

**Comment by ThePlayerZero** [comment]
Thank you! I fixed it.
