### ISSUE TITLE
Wide-screen Support Issue

### ISSUE THREAD

**Issue by ThePlayerZero** [ThePlayerZero/Open-Fantasy#2]
I don't know how to fix this, does anybody else?: ![image](https://user-images.githubusercontent.com/68795576/177058382-46ab314d-0e38-44e5-9d2f-784fd01a02f3.png)

**Comment by DarthNihilus1** [comment]
You have to modify the egg file in someway to support widescreen
My temporary solution for tt galaxy was just to fill the background with a blue color

**Comment by DarthNihilus1** [comment]
Also even after you fix the image so its widescreen, honestly should probably remove the rounded squares in the background do we even need them lol

**Comment by ThePlayerZero** [comment]
> Also even after you fix the image so its widescreen, honestly should probably remove the rounded squares in the background do we even need them lol

Yeah, probably should! I don't know how to do it though.
